---
- hosts: all
  roles:

  # osx config
  # - role: dock
  #   apps:
  #   - "/Applications/Utilities/Activity Monitor.app"
  #   - /Applications/Skype.app
  #   - /Applications/Adium.app
  #   - /Applications/Safari.app
  #   - /Applications/iTerm.app
  #   - /Applications/Atom.app
  #   - /Applications/Spotify.app
  #   folders:
  #   - path: ~/
  #   - path: ~/Documents
  #   - path: ~/Downloads
  #     sort: datemodified
  # - role: dashboard
  #   disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline

  # cli
  # shell tooling
  - role: git
    git_user_name: Nick Steffens
    git_user_email: nsteffens@gmail.com

  # Make sure the path prefix is there for the legit/hub shims
  - role: env_path
  - role: legit
  - role: hub

  - role: brew_package
    package_name: vim
  - role: brew_package
    package_name: ack
  - role: brew_package
    package_name: autossh
  - role: brew_package
    package_name: coreutils
  - role: brew_package
    package_name: findutils
  - role: brew_package
    package_name: imagemagick
  - role: brew_package
    package_name: pcre
  - role: brew_package
    package_name: sqlite
  - role: brew_package
    package_name: wget
  - role: brew_package
    package_name: docker
  - role: brew_package
    package_name: boot2docker
  # - role: pow


  ## languages
  - role: brew_package
    package_name: node
  - role: rbenv

  # Ruby gems
  - role: gem_package
    package_name: bundler
  - role: gem_package
    package_name: rails
  - role: gem_package
    package_name: coffee-rails
  - role: gem_package
    package_name: haml-rails
  - role: gem_package
    package_name: powder

  # Node packages
  - role: npm_package
    package_name: grunt
  - role: npm_package
    package_name: bower
  - role: npm_package
    package_name: yo
  # - role: npm_package
  #   package_name: ember-cli
  - role: npm_package
    package_name: coffee-script
  - role: npm_package
    package_name: katon
  - role: npm_package
    package_name: harp
  - role: npm_package
    package_name: sails
  - role: npm_package
    package_name: geddy



  # - role: cask_package
  #   package_name: java
  # - role: brew_package
  #   package_name: android-sdk

  ## databases
  - role: brew_package
    package_name: postgres
  - role: brew_package
    package_name: mongodb

  ## deployment
  - role: brew_package
    package_name: heroku-toolbelt
  # - role: brew_package
  #   package_name: ansible # Hey ! Already there !

  # gui
  ## text editors
  - role: cask_package
    package_name: atom

  # misc tools
  - role: cask_package
    package_name: skitch
  - role: cask_package
    package_name: dropbox
  - role: cask_package
    package_name: skype
  - role: cask_package
    package_name: adium
  - role: cask_package
    package_name: vlc
  - role: cask_package
    package_name: iterm2
